const U = (id, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const services = [
  {
    slug: "radiographic-testing",
    number: "01",
    title: "Radiographic Testing & Inspection",
    short: "X-ray and gamma-ray inspection to detect internal defects in welds, castings and pipes.",
    description: "Radiographic Testing (RT) is a non-destructive method using X-rays or gamma rays to detect internal defects in materials.",
    applications: ["Weld inspection", "Casting evaluation", "Pipeline integrity", "Pressure vessel walls"],
    industries: ["Aerospace", "Oil & Gas", "Petrochemical", "Power Generation"],
    benefits: ["Detects internal flaws", "Permanent record", "High-resolution imaging", "ASME/ASTM compliant"],
    standards: ["ASME Sec. V", "ASTM E94", "ASNT SNT-TC-1A", "ISO 17636"],
    image: "/services_photos/Radiographic Testing & Inspection.png",
  },
  {
    slug: "ultrasonic-testing",
    number: "02",
    title: "Ultrasonic Testing & Inspection",
    short: "High-frequency sound waves to identify internal flaws in castings, forgings and welds.",
    description: "Ultrasonic Testing (UT) uses high-frequency sound waves to detect internal flaws in materials.",
    applications: ["Forging inspection", "Weld scanning", "Lamination checks", "Thickness profiling"],
    industries: ["Oil & Gas", "Manufacturing", "Aerospace", "Defence"],
    benefits: ["No radiation", "Instant results", "Deep penetration", "Portable equipment"],
    standards: ["ASME Sec. V", "ASTM E114", "ISO 16810"],
    image: "/services_photos/Industrial ultrasonic testing.png",
  },
  {
    slug: "magnetic-particle-inspection",
    number: "03",
    title: "Magnetic Particle Inspection (MPI)",
    slug: "magnetic-particle-inspection",
    short: "Electromagnetic detection of surface and subsurface flaws in ferromagnetic parts. ",
    description: "Electromagnetic detection of surface and near-surface flaws in ferromagnetic materials.",
    applications: ["Crankshafts", "Crane hooks", "Weld toes", "Forged components"],
    industries: ["Automotive", "Construction", "Marine", "Manufacturing"],
    benefits: ["Fast inspection", "Visual results", "Subsurface detection", "Low cost per part"],
    standards: ["ASME Sec. V Art. 7", "ASTM E709", "ISO 9934"],
    image: "/services_photos/Magnetic particle inspection.png",
  },
  {
    slug: "liquid-penetrant-inspection",
    number: "04",
    title: "Liquid Penetrant Inspection (LPI)",
    short: "Dye-penetrant testing for open surface defects, porosity and fine cracks.",
    description: "Dye-penetrant testing for detecting open surface defects, porosity and fine cracks.",
    applications: ["Aerospace components", "Welds", "Forgings", "Castings"],
    industries: ["Aerospace", "Defence", "Petrochemical", "Automotive"],
    benefits: ["Works on any non-porous material", "High sensitivity", "Portable", "Economical"],
    standards: ["ASME Sec. V Art. 6", "ASTM E165", "ISO 3452"],
    image: "/services_photos/liquid-penetrant-inspection.png",
  },
  {
    slug: "visual-inspection",
    number: "05",
    title: "Visual Inspection",
    short: "Direct and aided visual examination to identify surface defects and weld quality.",
    description: "Direct and aided visual examination for surface defects and weld quality.",
    applications: ["Weld surface", "Corrosion mapping", "Coating defects", "Fabrication QC"],
    industries: ["All sectors"],
    benefits: ["Immediate results", "Low cost", "No special prep", "Documented imagery"],
    standards: ["AWS D1.1", "ASME Sec. V Art. 9", "API 1104"],
    image: "/services_photos/visual-inspection.png",
  },
  {
    slug: "third-party-inspection",
    number: "06",
    title: "Third Party Inspection Services",
    short: "Independent compliance verification for products, processes and systems.",
    description: "Independent third-party assessment for compliance and quality verification.",
    applications: ["Vendor inspection", "Pre-shipment", "Project monitoring", "Audit programs"],
    industries: ["Oil & Gas", "Power", "Defence", "Construction"],
    benefits: ["Unbiased verification", "Risk reduction", "Regulatory compliance", "Documented assurance"],
    standards: ["ISO/IEC 17020", "ASME", "API", "Client specifications"],
    image:"/services_photos/third-party-inspection.png",
  },
  {
    slug: "weld-inspection",
    number: "07",
    title: "Weld Inspection Services",
    short: "Comprehensive NDT and visual weld evaluation against applicable codes.",
    description: "Comprehensive inspection of welds using multiple NDT methods.",
    applications: ["Structural steel", "Pressure piping", "Pipelines", "Storage tanks"],
    industries: ["Construction", "Oil & Gas", "Power", "Manufacturing"],
    benefits: ["Code compliance", "Defect prevention", "Audit trail", "CWI-certified team"],
    standards: ["AWS D1.1/D1.5", "ASME Sec. IX", "API 1104"],
    image: "/services_photos/weld-inspection.png",
  },
  {
    slug: "welder-qualification",
    number: "08",
    title: "Welder Qualification (WPS/PQR/WPQ)",
    short: "Procedure and performance qualification per national and international codes.",
    description: "Welder and procedure qualification as per international standards.",
    applications: ["New welder onboarding", "Procedure development", "Audit support"],
    industries: ["Manufacturing", "Oil & Gas", "Construction", "Shipbuilding"],
    benefits: ["Code-compliant procedures", "Skilled workforce", "Quality assurance"],
    standards: ["ASME Sec. IX", "AWS D1.1", "ISO 9606", "EN 287"],
    image: "/services_photos/welder-qualification.png",
  },
  {
    slug: "welding-machine-calibration",
    number: "09",
    title: "Welding Machine Calibration",
    short: "Precise voltage and amperage calibration for consistent weld quality.",
    description: "Calibration of welding machines for accurate voltage and amperage.",
    applications: ["MIG/TIG/SMAW units", "Fabrication shops", "Construction sites"],
    industries: ["Manufacturing", "Construction", "Oil & Gas"],
    benefits: ["Process control", "Defect prevention", "Audit-ready records"],
    standards: ["AWS A5", "ISO 17662", "ANSI/AWS B5.4"],
    image: "/services_photos/welding-machine-calibration.png",
  },
  {
    slug: "surface-roughness-testing",
    number: "10",
    title: "Surface Roughness Testing",
    short: "Precision measurement of surface texture for performance-critical components.",
    description: "Measurement of surface roughness (Ra, Rz) for critical components.",
    applications: ["Machined parts", "Sealing surfaces", "Bearings", "Aerospace finishes"],
    industries: ["Aerospace", "Automotive", "Manufacturing"],
    benefits: ["Precision Ra/Rz values", "Portable equipment", "Process improvement"],
    standards: ["ISO 4287", "ASME B46.1"],
    image: "/services_photos/surface-roughness-testing.png",
  },
  {
    slug: "positive-material-identification",
    number: "11",
    title: "Positive Material Identification (PMI)",
    short: "Alloy verification using portable XRF to confirm material grade.",
    description: "Alloy composition verification using portable XRF analyzer.",
    applications: ["Pipe spool verification", "Vendor incoming QC", "Refinery shutdowns"],
    industries: ["Oil & Gas", "Power", "Chemical", "Aerospace"],
    benefits: ["Instant alloy ID", "Non-destructive", "Mix-up prevention"],
    standards: ["API RP 578", "ASTM E1476"],
    image: "/services_photos/positive-material-identification.png",
  },
  {
    slug: "ultrasonic-thickness-testing",
    number: "12",
    title: "Ultrasonic Thickness Testing",
    short: "High-frequency measurement of remaining wall thickness in pipes, tanks and hulls.",
    description: "Measurement of material thickness using ultrasonic technique.",
    applications: ["Pipeline CUI", "Tank shell mapping", "Hull plating"],
    industries: ["Oil & Gas", "Marine", "Petrochemical"],
    benefits: ["Single-side access", "Accurate to 0.01 mm", "Trends over time"],
    standards: ["ASTM E797", "API 510/570/653"],
    image: "/services_photos/ultrasonic-thickness-testing.png",
  },
  {
    slug: "ultrasonic-hardness-testing",
    number: "13",
    title: "Ultrasonic Hardness Testing",
    short: "Portable hardness measurement without significant surface damage.",
    description: "Non-destructive portable hardness testing.",
    applications: ["Heat-treat verification", "In-situ shaft testing", "Failure analysis"],
    industries: ["Manufacturing", "Power", "Automotive"],
    benefits: ["Portable", "Non-marring", "Multiple scales"],
    standards: ["ASTM A1038", "DIN 50159"],
    image: "/services_photos/ultrasonic-hardness-testing.png",
  },
  {
    slug: "leak-test",
    number: "14",
    title: "Leak Test (Hydro/Pneumatic)",
    short: "Hydrostatic and pneumatic pressure tests for vessels, pipes and tanks.",
    description: "Hydrostatic and pneumatic leak testing for pressure equipment.",
    applications: ["Pressure vessels", "Process piping", "Storage tanks", "Pipelines"],
    industries: ["Oil & Gas", "Chemical", "Power", "Petrochemical"],
    benefits: ["Code-mandated proof", "Leak localization", "Safety verification"],
    standards: ["ASME Sec. VIII", "B31.3", "API 510/570/653"],
    image: "/services_photos/leak-test.png",
  },
  {
    slug: "boroscopy",
    number: "15",
    title: "Boroscopy / Borescope Testing",
    short: "Camera-equipped probes inspect internal cavities and welds.",
    description: "Internal visual inspection using borescope camera systems.",
    applications: ["Turbine blade inspection", "Heat exchanger tubes", "Engine internals"],
    industries: ["Aerospace", "Power", "Oil & Gas"],
    benefits: ["No disassembly", "HD video record", "Cost effective"],
    standards: ["ASME Sec. V Art. 9", "ASTM E2862"],
    image: "/services_photos/boroscopy.png",
  },
  {
    slug: "micro-structure-testing",
    number: "16",
    title: "Micro Structure Testing",
    short: "Metallographic evaluation of grain structure and heat-treatment quality.",
    description: "Metallographic and microstructural analysis of materials.",
    applications: ["Weld macro/micro", "Heat-treat verification", "Failure analysis"],
    industries: ["Aerospace", "Power", "Defence", "Manufacturing"],
    benefits: ["Phase identification", "Grain size analysis", "ASTM compliant"],
    standards: ["ASTM E3", "ASTM E112", "ASTM E407"],
    image: "/services_photos/micro-structure-testing.png",
  },
  {
    slug: "failure-analysis",
    number: "17",
    title: "Failure Analysis Testing",
    short: "Systematic root-cause investigation of component failures.",
    description: "Root cause failure analysis of components and systems.",
    applications: ["Cracked shafts", "Burst pipes", "Bearing failures", "Weld failures"],
    industries: ["Power", "Oil & Gas", "Aerospace", "Automotive"],
    benefits: ["Root-cause identification", "Recurrence prevention", "Forensic report"],
    standards: ["ASM Handbook Vol. 11", "ASTM E1820"],
    image: "/services_photos/Failure Analysis Testing.png",
  },
  {
    slug: "corrosion-testing",
    number: "18",
    title: "Corrosion Testing",
    short: "Long-term corrosion evaluation for chemical and pharmaceutical equipment.",
    description: "Corrosion resistance testing under simulated environments.",
    applications: ["Vessel internals", "Heat exchangers", "Storage tanks"],
    industries: ["Pharmaceutical", "Chemical", "Petrochemical"],
    benefits: ["Material selection support", "Lifetime prediction", "Failure prevention"],
    standards: ["ASTM G48", "ASTM A262", "NACE TM0177"],
    image: "/services_photos/corrosion-testing.png",
  },
  {
    slug: "painting-inspections",
    number: "19",
    title: "Painting Inspections",
    short: "Coating quality, thickness, adhesion and surface preparation verification.",
    description: "Inspection of painting and coating systems.",
    applications: ["Structural steel", "Tanks & vessels", "Pipelines", "Marine assets"],
    industries: ["Marine", "Oil & Gas", "Infrastructure"],
    benefits: ["Coating life extension", "Defect prevention", "NACE/SSPC compliant"],
    standards: ["SSPC", "NACE", "ISO 12944"],
    image: "/services_photos/painting-inspections.png",
  },
  {
    slug: "hot-dip-galvanizing",
    number: "20",
    title: "Hot Dip Galvanizing Inspections",
    short: "Coating thickness, uniformity and adhesion checks per standards.",
    description: "Inspection of hot-dip galvanizing coating quality.",
    applications: ["Structural members", "Transmission towers", "Fasteners"],
    industries: ["Infrastructure", "Power", "Telecom"],
    benefits: ["Long coating life", "Compliance verification", "On-site inspection"],
    standards: ["ASTM A123", "ISO 1461", "AS/NZS 4680"],
    image:"/services_photos/Hot Dip Galvanizing Inspections.png",
  },
];

export const industries = [
  { name: "Aerospace", image: "/hero_section/flight.jpg",width: 800 },
  { name: "Defence & Military", image: "/industries/milatary.jpg",width: 800 },
  { name: "Automotive", image: "/industries/Automotive.jpg",width: 800 },
  { name: "Petrochemical", image: "/industries/Petrochemica.jpg",width: 800 },
  { name: "Oil & Gas", image: "/industries/Oil & Gas.jpg",width: 800 },
  { name: "Manufacturing", image: "/industries/Manufacturing.jpg",width: 800 },
  { name: "Construction", image: "/industries/Construction.jpg",width: 800 },
  { name: "Power Generation", image: "/industries/Power Generation.jpg",width: 800 },
  { name: "Chemical industries", image: "/industries/Chemical industries.png",width: 800 },
  { name: "Nuclear",image: "/industries/Nuclear.jpg",width: 800 },
  { name: "Medical", image: "/industries/Medical.png",width: 800 },
  { name: "Cement",image: "/industries/Cement.jpg",width: 800 },
  { name: "Aviation", image: "/industries/Aviation.jpg",width: 800 },
  { name: "Additive Manufacturing", image: "/industries/Additive Manufacturing.jpg",width: 800 },
  { name: "Paper Industries", image: "/industries/Paper Industries.jpg",width: 800 },
];

export const galleryImages = [
  // Service Images (Added)
  "/services_photos/Radiographic Testing & Inspection.png",
  "/services_photos/Industrial ultrasonic testing.png",
  "/services_photos/Magnetic particle inspection.png",
  "/services_photos/liquid-penetrant-inspection.png",
  "/services_photos/visual-inspection.png",
  "/services_photos/third-party-inspection.png",
  "/services_photos/weld-inspection.png",
  "/services_photos/welder-qualification.png",
  "/services_photos/welding-machine-calibration.png",
  "/services_photos/surface-roughness-testing.png",
  "/services_photos/positive-material-identification.png",
  "/services_photos/ultrasonic-thickness-testing.png",
  "/services_photos/ultrasonic-hardness-testing.png",
  "/services_photos/leak-test.png",
  "/services_photos/boroscopy.png",
  "/services_photos/micro-structure-testing.png",
  "/services_photos/Failure Analysis Testing.png",
  "/services_photos/corrosion-testing.png",
  "/services_photos/painting-inspections.png",
  "/services_photos/Hot Dip Galvanizing Inspections.png",
];

export const heroImages = [
  "/hero_section/1.png",
 
   "/hero_section/4.png",
   "/hero_section/3.png",
   "/hero_section/2.png",
 "/hero_section/industry.jpg",
 "/hero_section/sidewing.jpg",
  
];

export const company = {
  name: "VETECH NDT & Metallurgical Services Pvt. Ltd.",
  shortName: "VETECH",
  address: "H No: 5-35/53/A, 1st Floor, Prashanthinagar, Industrial Development Area, Hyderabad – 500072",
  emails: ["customersupport@vetechndt.com", "vetechndt@gmail.com"],
  phones: ["+91 8919076338", "+91 7794953838"],
  website: "www.vetechndt.com",
  gst: "36AALCV2977P1ZA",
};